# Path to your config files.
export CONFIG_FILES=$HOME/configFiles

# Path to environemnt files.
export ENV_FILES=$CONFIG_FILES/env

# Path to your oh-my-zsh installation.
export ZSH=$CONFIG_FILES/.oh-my-zsh

# Path to your zsh root folder.
export ZSH_ROOT=$CONFIG_FILES/zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="powerlevel9k"

# Zsh  Prompt Configuration
source $ZSH_ROOT/prompt

# Zsh Settings
source $ZSH_ROOT/settings

# Global Aliases
source $ENV_FILES/aliases

# Global Settings
source $ENV_FILES/settings
source $ENV_FILES/settings_private

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(ant brew brew-cask colored-man-pages common-aliases copydir copyfile git gitfast gradle grunt gulp history jira node npm osx sublime sudo textmate z zsh-syntax-highlighting)

# User configuration

# export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

# Autoloading Functions
fpath=(/usr/local/share/zsh-completions $fpath)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
