# Path to your config files.
export CONFIG_FILES=$HOME/configFiles

# Path to environemnt files.
export ENV_FILES=$CONFIG_FILES/env

# Path to your bash root folder.
export BASH_ROOT=$CONFIG_FILES/bash

# Included Bash files

source $BASH_ROOT/bash_prompt
source $BASH_ROOT/git_prompt
source $BASH_ROOT/settings
source $BASH_ROOT/aliases

source $ENV_FILES/aliases
source $ENV_FILES/settings

if [ -f ~/.bashrc ] ; then
	source ~/.bashrc ;
fi

if [ -f "$HOME/.bash_profile.$USER" ]; then
	. "$HOME/.bash_profile.$USER"
fi

if [ -f $BASH_COMPLETION_PATH ]; then
	. $BASH_COMPLETION_PATH
fi

[[ -s $BASH_AUTOJUMP ]] && . $BASH_AUTOJUMP